#219 Provide ability to define StorageClass for Databases
quay/quay-operator pull request #229
Opened 2020-05-25 14:05 UTC by drichtarik

Not sure about constants.go, defaults.go or resource/types.go edits
deyployments.go has comment section that I saved if it proves to be somewhat right approach

2020-05-26 05:47 UTC, sabre1041 requested changes
Looking good.  Made a few recommendations on some changes for the next draft iteration

2020-05-26 05:47 UTC, sabre1041 commented on pkg/controller/quayecosystem/constants/constants.go
> +	PersistentVolumeStorageClassName = "storageClassName"
No need for this constant value as no default will be used

2020-05-26 05:47 UTC, sabre1041 commented on pkg/controller/quayecosystem/provisioning/provision.go
> +		databasePvc := resources.GetDatabasePVCDefinition(meta, r.quayConfiguration.QuayEcosystem.Spec.Clair.Database.VolumeSize, &r.quayConfiguration.QuayEcosystem.Spec.Quay.Database.StorageClass)
Should be Clair's database reference and not Quay

2020-05-26 05:47 UTC, sabre1041 commented on pkg/controller/quayecosystem/resources/deployments.go
> +	/*	if !utils.IsZeroOfUnderlyingType(database.StorageClass) {
Can probably remove this snippet

2020-05-26 05:47 UTC, sabre1041 commented on pkg/controller/quayecosystem/resources/types.go
> +	StorageClass        string
This value is not needed

2020-05-26 05:47 UTC, sabre1041 commented on pkg/controller/quayecosystem/resources/storage.go
>  		},
Take a look at the method above for how the StorageClass is being added to the object. It should only be added if the value is defined and is not an empty string

2020-05-26 13:21 UTC, drichtarik commented
Thank you for the input and review. Updated. Hopefully I didn't miss anything.

2020-05-26 15:39 UTC, sabre1041 commented
@drichtarik this looks very good!

2020-05-27 14:01 UTC, sabre1041 requested changes
Can you generate the CRD's (4.x and 3.x) along with the generated classes + openapi specs. otherwise we should be good!

2020-05-30 03:12 UTC, sabre1041 approved these changes
LGTM

2020-05-30 03:12 UTC, merged